#!/bin/bash
docker-compose --file docker-compose.yml up -d
sleep 5s

ansible-playbook site.yml -i ./inventory/prod.yml -c /etc/ansible/ansible.cfg

echo 'start sleeping'
sleep 20s
docker-compose down -v
